import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';

import styles from '@/styles/Home.module.css'

const theme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#9fa8da',
    },
    secondary: {
      main: '#ff8a65',
    },
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main, 'main'].join(' ')}>
        <Typography>
          Welcome to the home page!
        </Typography>
      </main>
    </ThemeProvider>
  )
}
